name: CreeperModifications
main: com.sirbassington.creepermodifications.CreeperModifications
author: SirBassington
version: 0.3.0 Alpha
api-version: 1.13
description: "Modifies creepers to no longer destroy blocks as a result of creeper explosion and to cause creeper to emit status effects during said explosion. Creates status effects on explosion event for added surprise to caught-off-guard players!"